### ISSUE TITLE
[feature] 서버 환경 세팅 및 투표 데이터 서명화

### ISSUE THREAD

**Issue by janghw0126** [janghw0126/CryptoVoting-Platform#1]
## 📄 Description
- 서버 환경 세팅 및 서명 검증을 기반으로 한 투표 시스템을 구현합니다.

## ✅ TODO
- [x] 서버 환경 세팅
- [x] 클라이언트로부터 수신한 투표 데이터 서명
- [x] 서명된 데이터를 클라이언트에게 반환

## ✏️ ETC
.

## ⌛Deadline
12..06~
