### ISSUE TITLE
[feature] 클라이언트 환경 세팅 및 투표 데이터 암호화

### ISSUE THREAD

**Issue by janghw0126** [janghw0126/CryptoVoting-Platform#3]
## 📄 Description
- 클라이언트 환경 세팅 및 공개키를 기반으로 한 투표 데이터의 암호화를 구현합니다.

## ✅ TODO
- [x] 클라이언트 환경 세팅
- [x] 서버로부터 공개키를 받아와서 투표 데이터를 RSA를 이용해 암호화
- [x] 서버로부터 서명된 데이터를 받아 유효성을 검증

## ✏️ ETC
.

## ⌛Deadline
12.06~
